### ISSUE TITLE
Loading a path that begins with the word "media" throws a 403 error.

### ISSUE THREAD

**Issue by travisrisner** [clayfreeman/shared-hosting#1]
When loading a path that begins with the word media, for example `/mediation`, a 403 error is thrown.

**Comment by travisrisner** [comment]
Would it be better if [joomla35-common.conf](https://github.com/clayfreeman/shared-hosting/blob/3a056e2d289187e6a7c2c290722f3b065a165063/nginx/templates/joomla35-common.conf#L5) was changed to `location = /media {`?

The same thing would more than likely apply to the joomla25 nginx template as well.

**Comment by clayfreeman** [comment]
FIxed
